export const errors = {
  VALIDATION_ERROR: 'validationError',
  VALID_EMAIL_SHOULD_BE_PROVIDED: 'validEmailShouldBeProvided',
  PASSWORD_SHOULD_BE_FROM_SIX_TO_TWENTY_SYMBOLS: 'passwordShouldBeFrom6To20Symbols',
  USER_WITH_EMAIL_DOES_NOT_EXISTS: 'userWithEmailDoesNotExists',
  INVALID_EMAIL_OR_PASSWORD_SPECIFIED: 'invalidEmailOrPasswordSpecified',
  NAME_SHOULD_BE_FROM_THREE_TO_THIRTY_SYMBOLS: 'nameShouldBeFromThreeToThirtySymbols',
  PASSWORD_CONFIRMATION_SHOULD_MATCH: 'passwordConfirmationShouldMatch',
  EMAIL_ALREADY_IN_USE: 'emailAlreadyInUse',
  NETWORK_ERROR: 'Network Error',
  CHECK_AUTH_NETWORK_ERROR: 'checkAuthNetworkError',
  USER_WITH_MAIL_DOES_NOT_EXISTS: 'userWithMailDoesNotExists',
  INVALID_PASSWORD_SPECIFIED: 'invalidPasswordSpecified',
  PASSWORD_MUST_BE_DIFFERENT_WITH_PREV_ONE: 'passwordMustBeDifferentWithPrevOne',
};
